version: '3.8'
services:

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build:
      dockerfile: Dockerfile
      target: prod
    image: app-streamlit-prod:latest
    ports:
      - "8501:8501"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://user:pass@mongodb:27017

volumes:
  mongo-data:
